### ISSUE TITLE
حول قسم الاخبار

### ISSUE THREAD

**Issue by bmayoub** [mslaraba/TouggourtiWeb#23]
أرى أن يتم تأخير بث أخبار تقرت حتى نجد من يتطوع يوميا لإضافة أخبار جديدة، أما اذا انطلق العمل وكانت الأخبار متأخرة وغير مواكبة للتطورات فسينفر الناس من التطبيق

**Comment by mslaraba** [comment]
نعم ولكن يجب تحضير الكود أولا وعند وجود المتطوع نقوم فقط بإظهاره

**Comment by bmayoub** [comment]
جيد
